'use strict';

const DATAPOINTS = {
	'Approx. Altitude': { type: 'number', role: 'value.altitude', read: true, write: false, unit: 'm' },
	'PM2.5': { type: 'number', role: 'value', read: true, write: false, unit: 'ug/m3' },
	A0: { type: 'number', role: 'value', read: true, write: false },
	A1: { type: 'number', role: 'value', read: true, write: false },
	A2: { type: 'number', role: 'value', read: true, write: false },
	A3: { type: 'number', role: 'value', read: true, write: false },
	Action: { type: 'string', role: 'value', read: true, write: true },
	AirQuality: { type: 'number', role: 'value', read: true, write: false, unit: '%' },
	Analog0: { type: 'number', role: 'value', read: true, write: false },
	Analog1: { type: 'number', role: 'value', read: true, write: false },
	Analog2: { type: 'number', role: 'value', read: true, write: false },
	Analog3: { type: 'number', role: 'value', read: true, write: false },
	ApparentPower: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'VA' },
	Arm: { type: 'number', role: 'value', read: true, write: true },
	BSSId: { type: 'string', role: 'state', read: true, write: false },
	BatteryPercentage: { type: 'number', role: 'value', read: true, write: false, unit: '%' },
	BatteryVoltage: { type: 'number', role: 'value.voltage', read: true, write: false, unit: 'V' },
	Blue: { type: 'number', role: 'level.color.blue', read: true, write: true, min: 0, max: 100 },
	Button1: { type: 'boolean', role: 'button', read: true, write: false },
	Button2: { type: 'boolean', role: 'button', read: true, write: false },
	Button3: { type: 'boolean', role: 'button', read: true, write: false },
	Button4: { type: 'boolean', role: 'button', read: true, write: false },
	Button5: { type: 'boolean', role: 'button', read: true, write: false },
	Button6: { type: 'boolean', role: 'button', read: true, write: false },
	Button7: { type: 'boolean', role: 'button', read: true, write: false },
	Button8: { type: 'boolean', role: 'button', read: true, write: false },
	CT: { type: 'number', role: 'level.color.temp', read: true, write: true, min: 153, max: 500 },
	CW: { type: 'number', role: 'level.color.coldwhite', read: true, write: true },
	CW_POWER: { type: 'boolean', role: 'switch.light', read: true, write: true },
	CarbonDioxide: { type: 'number', role: 'value.CO2', read: true, write: false, unit: 'ppm' },
	Channel: { type: 'number', role: 'level', read: true, write: true },
	Color: { type: 'string', role: 'level.color.rgb', read: true, write: true },
	Counter1: { type: 'number', role: 'value', read: true, write: false },
	Counter2: { type: 'number', role: 'value', read: true, write: false },
	Counter3: { type: 'number', role: 'value', read: true, write: false },
	Counter4: { type: 'number', role: 'value', read: true, write: false },
	Current: { type: 'number', role: 'value.current', read: true, write: false, unit: 'A' },
	CurrentNeutral: { type: 'number', role: 'value.current', read: true, write: false, unit: 'A' },
	Data: { type: 'string', role: 'state', read: true, write: true },
	DewPoint: { type: 'number', role: 'value.temperature', read: true, write: false, unit: '°C' },
	Dimmer: { type: 'number', role: 'level.dimmer', read: true, write: true, min: 0, max: 100 },
	Distance: { type: 'number', role: 'value', read: true, write: false, unit: 'cm' },
	Downtime: { type: 'string', role: 'state', read: true, write: false },
	ExportActive: { type: 'number', role: 'value.power.produced', read: true, write: false, unit: 'kWh' },
	Factor: { type: 'number', role: 'value', read: true, write: false },
	Fade: { type: 'boolean', role: 'switch', read: true, write: true },
	Frequency: { type: 'number', role: 'value.frequency', read: true, write: false, unit: 'Hz' },
	Green: { type: 'number', role: 'level.color.green', read: true, write: true, min: 0, max: 100 },
	HSBColor: { type: 'string', role: 'value.hsb', read: true, write: true },
	Hostname: { type: 'string', role: 'info.address', read: true, write: false },
	Hue: { type: 'number', role: 'level.color.hue', read: true, write: true, min: 0, max: 360 },
	Humidity: { type: 'number', role: 'value.humidity', read: true, write: false, unit: '%' },
	IPAddress: { type: 'string', role: 'info.ip', read: true, write: false },
	IPaddress: { type: 'string', role: 'info.ip', read: true, write: false },
	IRSend: { type: 'string', role: 'state', read: true, write: true },
	Illuminance: { type: 'number', role: 'value.illuminance', read: true, write: false, unit: 'lx' },
	LED_Mode: { type: 'number', role: 'value', read: true, write: true },
	LedTable: { type: 'string', role: 'state', read: true, write: false },
	Light: { type: 'number', role: 'value', read: true, write: false, unit: 'lx' },
	Longitude: { type: 'number', role: 'value.gps.longitude', read: true, write: false, unit: '°' },
	Latitude: { type: 'number', role: 'value.gps.latitude', read: true, write: false, unit: '°' },
	Mode: { type: 'string', role: 'state', read: true, write: true },
	Module: { type: 'string', role: 'state', read: true, write: false },
	Noise: { type: 'number', role: 'value', read: true, write: false, unit: 'dB' },
	Output: { type: 'number', role: 'value', read: true, write: true },
	PM10: { type: 'number', role: 'value', read: true, write: false, unit: 'ug/m3' },
	PWM1: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM2: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM3: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM4: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM5: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM6: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM7: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PWM8: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 1023 },
	PulseTime1: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime2: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime3: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime4: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime5: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime6: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime7: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	PulseTime8: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 64900 },
	POWER: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER1: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER2: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER3: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER4: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER5: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER6: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER7: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER8: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER9: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER10: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER11: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER12: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER13: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER14: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER15: { type: 'boolean', role: 'switch', read: true, write: true },
	POWER16: { type: 'boolean', role: 'switch', read: true, write: true },
	Power: { type: 'number', role: 'value.power', read: true, write: false, unit: 'W' },
	PowerDelta: { type: 'number', role: 'value', read: true, write: false, unit: 'W' },
	PowerHigh: { type: 'number', role: 'value', read: true, write: false, unit: 'W' },
	PowerLow: { type: 'number', role: 'value', read: true, write: false, unit: 'W' },
	Pressure: { type: 'number', role: 'value.pressure', read: true, write: false, unit: 'hPa' },
	Protocol: { type: 'string', role: 'state', read: true, write: true },
	RGB_POWER: { type: 'boolean', role: 'switch.light', read: true, write: true },
	RSSI: { type: 'number', role: 'value.rssi', read: true, write: false },
	ReactivePower: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'var' },
	Red: { type: 'number', role: 'level.color.red', read: true, write: true, min: 0, max: 100 },
	Repeat: { type: 'number', role: 'value', read: true, write: true },
	RestartReason: { type: 'string', role: 'state', read: true, write: false },
	SHUTTER1: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER2: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER3: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER4: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER5: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER6: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER7: { type: 'number', role: 'value', read: true, write: false },
	SHUTTER8: { type: 'number', role: 'value', read: true, write: false },
	SSId: { type: 'string', role: 'info.ssid', read: true, write: false },
	Saturation: { type: 'number', role: 'level.color.saturation', read: true, write: true, min: 0, max: 255 },
	Scheme: { type: 'number', role: 'value', read: true, write: true, min: 0, max: 4, states: { 0: 'Single color', 1: 'Wakeup', 2: 'Cycle UP', 3: 'Cycle DOWN', 4: 'Random cycle' } },
	SeaPressure: { type: 'number', role: 'value.pressure', read: true, write: false, unit: 'hPa' },
	SleepMode: { type: 'string', role: 'state', read: true, write: false },
	Speed: { type: 'number', role: 'value', read: true, write: true },
	Status: { type: 'number', role: 'value', read: true, write: false },
	// Shutter sub-states (compound key: ShutterN_SubKey)
	Shutter1_Position: { type: 'number', role: 'level.blind', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter1_Direction: { type: 'number', role: 'value', read: true, write: false },
	Shutter1_Target: { type: 'number', role: 'value', read: true, write: false, min: 0, max: 100, unit: '%' },
	Shutter1_Tilt: { type: 'number', role: 'level.tilt', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter2_Position: { type: 'number', role: 'level.blind', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter2_Direction: { type: 'number', role: 'value', read: true, write: false },
	Shutter2_Target: { type: 'number', role: 'value', read: true, write: false, min: 0, max: 100, unit: '%' },
	Shutter2_Tilt: { type: 'number', role: 'level.tilt', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter3_Position: { type: 'number', role: 'level.blind', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter3_Direction: { type: 'number', role: 'value', read: true, write: false },
	Shutter3_Target: { type: 'number', role: 'value', read: true, write: false, min: 0, max: 100, unit: '%' },
	Shutter3_Tilt: { type: 'number', role: 'level.tilt', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter4_Position: { type: 'number', role: 'level.blind', read: true, write: true, min: 0, max: 100, unit: '%' },
	Shutter4_Direction: { type: 'number', role: 'value', read: true, write: false },
	Shutter4_Target: { type: 'number', role: 'value', read: true, write: false, min: 0, max: 100, unit: '%' },
	Shutter4_Tilt: { type: 'number', role: 'level.tilt', read: true, write: true, min: 0, max: 100, unit: '%' },
	Switch1: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch2: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch3: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch4: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch5: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch6: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch7: { type: 'boolean', role: 'switch', read: true, write: true },
	Switch8: { type: 'boolean', role: 'switch', read: true, write: true },
	TVOC: { type: 'number', role: 'value.tvoc', read: true, write: false, unit: 'ppb' },
	Temperature: { type: 'number', role: 'value.temperature', read: true, write: false, unit: '°C' },
	Time: { type: 'string', role: 'date', read: true, write: false },
	Today: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'kWh' },
	TodaySumExport: { type: 'number', role: 'value.power.produced', read: true, write: false, unit: 'kWh' },
	TodaySumImport: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'kWh' },
	Total: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'kWh' },
	TotalStartTime: { type: 'string', role: 'date', read: true, write: false },
	Uptime: { type: 'mixed', role: 'state', read: true, write: false },
	UvIndex: { type: 'number', role: 'value.uv', read: true, write: false },
	VCC: { type: 'number', role: 'value.voltage', read: true, write: false, unit: 'V' },
	Vcc: { type: 'number', role: 'value.voltage', read: true, write: false, unit: 'V' },
	Version: { type: 'string', role: 'state', read: true, write: false },
	Voltage: { type: 'number', role: 'value.voltage', read: true, write: false, unit: 'V' },
	WW: { type: 'number', role: 'level.color.white', read: true, write: true },
	WW_POWER: { type: 'boolean', role: 'switch.light', read: true, write: true },
	Wakeup: { type: 'string', role: 'state', read: true, write: true },
	Yesterday: { type: 'number', role: 'value.power.consumption', read: true, write: false, unit: 'kWh' },
	eCO2: { type: 'number', role: 'value.eco2', read: true, write: false, unit: 'ppm' },
};

module.exports = { DATAPOINTS };
